In [109]:
import numpy as np
import scipy.linalg as sp

In [2]:
state = {
    0 : "Burger",
    1 : "Pizza",
    2 : "Hotdog"
}
state

{0: 'Burger', 1: 'Pizza', 2: 'Hotdog'}

In [3]:
A = np.array([[0.2, 0.6, 0.2], [0.3, 0.0, 0.7], [0.5, 0.0, 0.5]])
A

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

### Simulating random walk

In [40]:
def sim(current_state,m,n):
    print(state[current_state],"--->",end=' ')
    while n>1:
        current_state= np.random.choice(list(state.keys()),p= m[current_state])
        print(state[current_state],"--->",end=" ")
        n-=1
    print("stop")

In [41]:
sim(0,A,20)

Burger ---> Burger ---> Burger ---> Burger ---> Burger ---> Hotdog ---> Hotdog ---> Hotdog ---> Burger ---> Hotdog ---> Burger ---> Burger ---> Pizza ---> Hotdog ---> Burger ---> Pizza ---> Burger ---> Pizza ---> Hotdog ---> Hotdog ---> stop


### Getting stationary distribution (π) using Monte Carlo approach

In [123]:
def get_pi(current_state,m,n):
    d={}
    d[current_state]= d.get(current_state,0)+1
    while n>1:
        current_state= np.random.choice(list(state.keys()),p= m[current_state])
        d[current_state]= d.get(current_state,0)+1
        n-=1
    return([i/sum(d.values()) for i in d.values()])

In [127]:
get_pi(0,A,10**6)

[0.351844, 0.211152, 0.437004]

In [128]:
pi= get_pi(0,A,10**6)

### Getting stationary distribution (π) using matrix multiplication

In [93]:
def get_pi(m,n):
    while n>0:
        m = m @ m
        n-=1
    print(m)

In [98]:
get_pi(A,5)

[[0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]
 [0.35211268 0.21126761 0.43661972]]


### Getting stationary distribution (π) using left eigen vectors

In [114]:
value,vector = sp.eig(A,right=False,left=True)

In [117]:
print(vector)

[[-0.58746336+0.j         -0.16984156-0.35355339j -0.16984156+0.35355339j]
 [-0.35247801+0.j          0.67936622+0.j          0.67936622-0.j        ]
 [-0.72845456+0.j         -0.50952467+0.35355339j -0.50952467-0.35355339j]]


In [129]:
left= vector[:,0]
left

array([-0.58746336+0.j, -0.35247801+0.j, -0.72845456+0.j])

In [130]:
pi_normalized = [(i/sum(left)).real for i in left]
pi_normalized

[0.352112676056338, 0.21126760563380279, 0.43661971830985913]

### Getting the probability of specific sequence

In [148]:
def get_proba(sequence,m,pi):
    prob=pi[sequence[0]]
    for i in range(1,len(sequence)):
            prob = prob* m[sequence[i-1],sequence[i]]            
    return prob
        

In [151]:
get_proba([1,2,2,2,0],A,pi)

0.0184825375