In [3]:
import numpy as np
import scipy.linalg as sp

### Defining states and transition matrix

In [7]:
state = {
    0 : "sunny",
    1 : "cloudy",
    2 : "rainy"
}
state

{0: 'sunny', 1: 'cloudy', 2: 'rainy'}

In [8]:
m = np.array([[0.6, 0.3, 0.1], [0.2, 0.3, 0.5], [0.4, 0.1, 0.5]])
m

array([[0.6, 0.3, 0.1],
       [0.2, 0.3, 0.5],
       [0.4, 0.1, 0.5]])

<h1 style="color:gold"> Weather Markov Chain </h1>

<img src="weather.png" width="570" height="400">

### Simulating random walk

In [9]:
def sim(current_state,m,n):
    print(state[current_state],"--->",end=' ')
    while n>1:
        current_state= np.random.choice(list(state.keys()),p= m[current_state])
        print(state[current_state],"--->",end=" ")
        n-=1
    print("stop")

In [10]:
sim(0,m,20)

sunny ---> rainy ---> rainy ---> rainy ---> sunny ---> cloudy ---> rainy ---> rainy ---> rainy ---> sunny ---> sunny ---> cloudy ---> cloudy ---> sunny ---> sunny ---> sunny ---> cloudy ---> cloudy ---> rainy ---> sunny ---> stop


### Getting stationary distribution (π) using Monte Carlo approach

In [11]:
def get_pi(current_state,m,n):
    d={}
    d[current_state]= d.get(current_state,0)+1
    while n>1:
        current_state= np.random.choice(list(state.keys()),p= m[current_state])
        d[current_state]= d.get(current_state,0)+1
        n-=1
    return([i/sum(d.values()) for i in d.values()])

In [14]:
pi= get_pi(0,m,10**6)

In [15]:
pi

[0.440307, 0.235488, 0.324205]

### Getting stationary distribution (π) using matrix multiplication

In [16]:
def get_pi(m,n):
    while n>0:
        m = m @ m
        n-=1
    print(m)

In [18]:
get_pi(m,5)

[[0.44117647 0.23529412 0.32352941]
 [0.44117647 0.23529412 0.32352941]
 [0.44117647 0.23529412 0.32352941]]


### Getting stationary distribution (π) using left eigen vectors

In [19]:
value,vector = sp.eig(m,right=False,left=True)

In [20]:
print(vector)

[[ 0.7407972 +0.j         -0.35355339+0.35355339j -0.35355339-0.35355339j]
 [ 0.39509184+0.j         -0.35355339-0.35355339j -0.35355339+0.35355339j]
 [ 0.54325128+0.j          0.70710678+0.j          0.70710678-0.j        ]]


In [21]:
left= vector[:,0]
left

array([0.7407972 +0.j, 0.39509184+0.j, 0.54325128+0.j])

In [22]:
pi_normalized = [(i/sum(left)).real for i in left]
pi_normalized

[0.44117647058823506, 0.2352941176470589, 0.3235294117647061]

### Getting the probability of specific sequence

In [23]:
def get_proba(sequence,m,pi):
    prob=pi[sequence[0]]
    for i in range(1,len(sequence)):
            prob = prob* m[sequence[i-1],sequence[i]]            
    return prob
        

In [24]:
get_proba([1,2,2,2,0],m,pi)

0.0117744